--#########################
-- HYPRLAND MASTER CONFIG #
--#########################

hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "1",
})

mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- Environment variables
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("HYPRCURSOR_SIZE", "40")
hl.env("DXVK_ASYNC", "1")
hl.env("SDL_VIDEODRIVER", "wayland")

require("modules/autostart")

-- Apperance modules
require("modules/color") -- Generated by matugen. Check ~/.config/matugen/templates/hyprcolor.lua
require("modules/apperance/animation")
require("modules/apperance/decoration")

-- Peripheral bindings
require("modules/bindings/keyboard")
require("modules/bindings/mouse")
require("modules/bindings/scripts")
require("modules/bindings/gesture")

-- Rules
require("modules/rules/workspaces")
require("modules/rules/windows")
require("modules/rules/layers")

-- Configs
require("modules/input")
require("modules/general")
