shell zsh
font_family             family="JetBrainsMono Nerd Font"
bold_font               family="JetBrainsMono Nerd Font", style='Bold'
italic_font             family='JetBrainsMono Nerd Font' style='SemiBold Italic'
bold_italic_font        family='JetBrainsMono Nerd Font' style='Bold Italic'
font_size               13.0
disable_ligatures       never
remember_window_size    no
unicode_input           yes
shell_integration       enabled

url_color               #e9f0ff
visual_bell_color       #ffece9
bell_border_color       #ffaea4
active_border_color     #e9f0ff
inactive_border_color   #bfc2cb
background              #111418
foreground              #ffffff
selection_foreground    #44474c
selection_background    #ffffff
active_tab_foreground   #000000
active_tab_background   #9fc5fa
inactive_tab_foreground #ffffff
inactive_tab_background #43474e
color0                  #000000
color1                  #ffece9
color2                  #fceaff
color3                  #e9f0ff
color4                  #e9f0ff
color5                  #d4b9df
color6                  #b8c3d7
color7                  #ffffff
color8                  #edf0f9
color9                  #ffaea4
color10                 #9fc5fa
color11                 #204977
color12                 #e9f0ff
color13                 #000000
color14                 #000000
color15                 #4e5055
