general {
  ignore_empty_input = true
}

auth {
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint to unlock
    present_message = Scanning fingerprint
    retry_delay = 100
  }
}

background {
 path = screenshot
 blur_passes = 2
 blur_size = 7

 color = rgb({{colors.surface.default.hex}})
 noise = 0.1
}

label {
  text = $TIME
  font_family = SF Pro weight=590
  color = rgb({{colors.on_surface.default.hex}})
  font_size = 100
  position = 0, 300
  halign = center
  valign = center
}

label {
  text = cmd[update:2000] date +"%A, %B %d"
  font_family = SF Pro Display Medium
  color = rgb({{colors.on_secondary.default.hex}})
  position = 0, 390
  font_size = 23
  halign = center
  valign = center
}

label {
  text = $USER
  font_family = SF Pro weight=509
  color = rgb({{colors.tertiary.default.hex}})
  position = 0, -400
}

label {
  text = $FPRINTPROMPT
  font_family = SF Pro weight=509
  color = rgb({{colors.tertiary.default.hex}})
  font_size = 14
  position = 0, -450
}

input-field {
  font_family = SF Pro weight=509
  size = 15%, 4%
  outline_thickness = 0
  inner_color = rgba({{colors.secondary.default.hex}}55)
  outer_color = rgba(255, 255, 255, 0)
  font_color = rgb({{colors.on_secondary.default.hex}})
  placeholder_text = Enter Password
  dots_center = false
  position = 0, 0
  rounding = 15
  halign = center
  valign = center
}
